name:
  .trash: ï‡¸
  .cargo: î¨
  a.out: ï’‰
extension:
  go: î˜§
  hs: î·
  rs: ğŸ¦€
filetype:
  socket: ó°†¨
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: ó°œ«
  special: ï‹œ
